'use client';

import Navbar from "../../components/Navbar";
import styles from "../../styles/Home.module.css";
import Searchbar from "../../components/Searchbar";
import Discover from "../../components/Discover";
import Blogs from "../../components/Blogs";
import Destination from "../../components/Destination";
import Events from "../../components/Events";
import Footer from "../../components/Footer";


export const metadata = {
  title: "Tricky Travelers",
  description: "Generated by create next app",
};


export default function Home() {
  return (
    <>
      <div>
        <Navbar />
        <div className={styles.imagecontainer}>
          <img src="/images/back.jpg" alt="Your Image" className={styles.image} />
          <div className={styles.desc}>
            <h1 >The Trickiest Travel Community</h1>
            <Searchbar/>
          </div>
        </div>
        <Discover/>
        <Destination/>
        <Blogs/> 
        <Events/> 
        <Footer/>
      </div>
    </>
  );
}
